name: as3_to_dart
description: Pure Actionscript to Dart Conversion Helper.
version: 0.1.0
homepage: https://github.com/sethladd/simple_http_server
authors: 
- Nils Döhring <nilsdoehring@gmail.com>
environment:
  sdk: ">=1.6.0-dev"
dependencies:
  examples_autogen:
    path: lib/examples_autogen
  args: any
  browser: any
  path: any
