name: as3_to_dart
description: Pure Actionscript to Dart Conversion Helper.
version: 0.1.0
homepage: https://github.com/blockforest/actionscript-to-dart
authors: 
- Nils Döhring <nilsdoehring@gmail.com>
environment:
  sdk: ">=1.6.0-dev"
dependencies:
  args: any
  browser: any
  path: any
  stagexl: 
   git : https://github.com/bp74/StageXL.git
  dotlight_working:
    path: lib/dotlight_working
  xmas_working:
    path: lib/xmas_working
